### ISSUE TITLE
请问这个插件支持国际版抖音吗？

### ISSUE THREAD

**Issue by gogo008** [sky-wei/xposed-aweme#1]
请问这个插件支持国际版抖音吗？

**Comment by gogo008** [comment]
国际版抖音play版现在版本号是2.5.6

**Comment by sky-wei** [comment]
暂时不支持。




Get Outlook for Android







On Sun, Jul 8, 2018 at 10:05 PM +0800, "gogo008" <notifications@github.com> wrote:












国际版抖音play版现在版本号是2.5.6
